apiVersion: batch/v1
kind: Job
metadata:
  name: post-install-job
  labels:
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded 
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      serviceAccount: {{ template "kyverno.admission-controller.serviceAccountName" . }}
      containers:
        - name: "build-kyverno-trust"
          image: {{ .Values.webhooksCleanup.image }}
          command:
            - '/bin/sh'
          args:
            - '-c'
            - 'cd /usr/local/sbin && sh build-trust.sh'
          volumeMounts:
          - mountPath: /usr/local/sbin
            name: build-kyverno-trust
          - mountPath: /mnt/platform
            name: host-path1
          - mountPath: /mnt/ca
            name: host-path2
          securityContext:
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
      volumes:
      - name: build-kyverno-trust
        configMap:
          name: build-kyverno-trust
          defaultMode: 0755
      - name: host-path1
        hostPath:
          path: /etc/pki/trust/anchors
      - name: host-path2
        hostPath:
          path: /etc/kubernetes/pki
