apiVersion: v1
kind: ConfigMap
metadata:
  name: build-kyverno-trust
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
data:
  build-trust.sh: |-
    #!/bin/bash
    CERT_PATH1="/mnt/platform/platform-ca-certs.crt"
    CERT_PATH2="/mnt/ca/ca.crt"
    cat "$CERT_PATH1" "$CERT_PATH2" > /tmp/combined-certs.crt
    kubectl create configmap kyverno-certs --from-file=ca-certificates=/tmp/combined-certs.crt --namespace=kyverno --dry-run=client -o yaml | kubectl apply -f -
    kubectl patch deployment kyverno-admission-controller -n kyverno --type=json -p='[
      {
        "op": "add",
        "path": "/spec/template/spec/volumes",
        "value": [
          {
            "name": "sigstore"
          },
          {
            "name": "ca-certificates",
            "configMap": {
              "name": "kyverno-certs",
              "items": [
                {
                  "key": "ca-certificates",
                  "path": "ca-certificates.crt"
                }
              ]
            }
          }
        ]
      },
      {
        "op": "add",
        "path": "/spec/template/spec/containers/0/volumeMounts",
        "value": [
          {
            "mountPath": "/.sigstore",
            "name": "sigstore"
          },
          {
            "name": "ca-certificates",
            "mountPath": "/etc/ssl/certs/ca-certificates.crt",
            "subPath": "ca-certificates.crt"
          }
        ]
      }
    ]'
    
