kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kyverno.admission-controller.name" . }}
  namespace: {{ template "kyverno.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kyverno.admission-controller.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kyverno.admission-controller.sAccountName" . }}
  namespace: {{ template "kyverno.namespace" . }}
