apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "kyverno.post-install-job.name" . }}
  labels:
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-upgrade,post-install
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      serviceAccount: {{ template "kyverno.post-install-job.sAccountName" . }}
      containers:
        - name: {{ template "kyverno.post-install-job.name" . }}
          image: {{ .Values.kyverno.buildKyvernoTrust.image.registry }}/{{ .Values.kyverno.buildKyvernoTrust.image.repository }}:{{ .Values.kyverno.buildKyvernoTrust.image.tag }}
          command:
            - '/bin/sh'
            - '-c'
            - |
              cd /usr/local/sbin && sh build-trust.sh
              # Waiting for Kyverno deployment to complete rollout
              kubectl rollout status deployment kyverno-admission-controller -n kyverno --timeout=60s
              # Waiting for 20 secs to avoid webhook timeouts. Known limitation in Kyverno w.r.t webhooks on 1.10.x.
              # sleep 20
          volumeMounts:
          - mountPath: /usr/local/sbin
            name: build-kyverno-trust
          - mountPath: /mnt/platform
            name: host-path1
          - mountPath: /mnt/ca
            name: host-path2
          securityContext:
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
      volumes:
      - name: build-kyverno-trust
        configMap:
          name: build-kyverno-trust
          defaultMode: 0755
      - name: host-path1
        hostPath:
          path: /etc/pki/trust/anchors
      - name: host-path2
        hostPath:
          path: /etc/kubernetes/pki
