apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kyverno.post-install-job.name" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-10"
rules:
- apiGroups: [""]
  resourceNames:
  - {{ include "kyverno.post-install-job.name" . }}
  resources: [podsecuritypolicies]
  verbs: [get, list, patch, create, delete, use]
- apiGroups: [""]
  resources: [configmaps]
  verbs: [get, list, patch, create, delete]
- apiGroups: ["apps"]
  resources: [deployments]
  verbs: [get, list, patch, create, delete]
- apiGroups: [""]
  resources: [pods]
  verbs: [list, get, delete,create]
