kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "kyverno.post-install-job.sAccountName" . }}
  annotations:
    "helm.sh/hook": post-upgrade,post-install
    "helm.sh/hook-weight": "-20"
