kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kyverno.pre-upgrade-job.name" . }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-10"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kyverno.pre-upgrade-job.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kyverno.pre-upgrade-job.sAccountName" . }}
  namespace: kyverno
