apiVersion: v1
kind: ConfigMap
metadata:
  name: delete-crd
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "1"
data:
  deleteCRD.sh: |-
    #!/bin/sh
    kubectl delete crd $(kubectl get crd -A | grep -i kyverno | awk '{print $1}')
