apiVersion: v2
type: application
name: cray-kyverno
version: 1.4.3
appVersion: v1.7.5
icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
description: Kubernetes Native Policy Management
keywords:
  - kubernetes
  - policy agent
  - validating webhook
  - admissions controller
dependencies:
  - name: kyverno
    repository: https://kyverno.github.io/kyverno/
    version: v2.5.5
home: https://github.com/Cray-HPE/cray-kyverno
sources:
  - https://github.com/kyverno/kyverno
maintainers:
  - name: ibrahim0809
    url: https://kyverno.io/
engine: gotpl
kubeVersion: ">=1.16.0-0"
annotations:
  artifacthub.io/images: |-
    - name: kyverno
      image: artifactory.algol60.net/csm-docker/stable/ghcr.io/kyverno/kyverno:v1.7.5
    - name: kyvernopre
      image: artifactory.algol60.net/csm-docker/stable/ghcr.io/kyverno/kyvernopre:v1.7.5
    - name: busybox
      image: artifactory.algol60.net/csm-docker/stable/docker.io/library/busybox:1.28.0-glibc
  artifacthub.io/license: MIT
