apiVersion: v2
type: application
name: cray-kyverno
version: v2.3.0
appVersion: v1.6.0
icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
description: Kubernetes Native Policy Management
keywords:
  - kubernetes
  - policy agent
  - validating webhook
  - admissions controller
dependencies:
  - name: kyverno
    repository: https://kyverno.github.io/kyverno/
    version: v2.3.0
home: https://kyverno.io/
sources:
  - https://github.com/kyverno/kyverno
maintainers:
  - name: ibrahim0809
    url: https://kyverno.io/
engine: gotpl
kubeVersion: ">=1.16.0-0"
annotations:
  artifacthub.io/images: |-
    - name: kyverno
      image: artifactory.algol60.net/csm-docker/stable/ghcr.io/kyverno/kyverno:v1.6.0
    - name: kyvernopre
      image: artifactory.algol60.net/csm-docker/stable/ghcr.io/kyverno/kyvernopre:v1.6.0
  artifacthub.io/license: MIT
