# Default values for cray-kyverno.
# This is a YAML-formatted file.
kyverno:
  upgrade:
  # -- Upgrading from v2 to v3 is not allowed by default, set this to true once changes have been reviewed.
    fromV2: true
  crds:
    migration:
      enabled: false
      image:
        registry: artifactory.algol60.net
        repository: csm-docker/stable/ghcr.io/kyverno/kyverno-cli
        tag: v1.13.4    
  features:
    backgroundScan:
      skipResourceFilters: false
    policyExceptions:      
      # -- Enables the feature
      enabled: true
      namespace: '*'      
  admissionController:
    config:
      webhooks: [{"namespaceSelector":{"matchExpressions":[{"key":"kubernetes.io/metadata.name","operator":"NotIn","values":["kube-system"]}]}}]
    initContainer:
      image:
        registry: artifactory.algol60.net
        repository: csm-docker/stable/ghcr.io/kyverno/kyvernopre
        tag: v1.13.4
      resources:
        limits:
          cpu: 6000m
          memory: 3Gi
        requests:
          cpu: 2000m
          memory: 1Gi
    container:
      image:
        registry: artifactory.algol60.net
        repository: csm-docker/stable/ghcr.io/kyverno/kyverno
        tag: v1.13.4
      resources:
        limits:
          cpu: 6000m
          memory: 3Gi
        requests:
          cpu: 2000m
          memory: 1Gi
    # Desired number of pods/replica
    replicas: 3
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - kyverno
          topologyKey: kubernetes.io/hostname

    priorityClassName: csm-high-priority-service

  test:
    image:
      repository: artifactory.algol60.net/csm-docker/stable/docker.io/library/busybox
      tag: 1.28.0-glibc
  cleanupController:
    image:
      registry: artifactory.algol60.net
      repository: csm-docker/stable/ghcr.io/kyverno/cleanup-controller
      tag: v1.13.4
    resources:
      limits:
        cpu: 6000m
        memory: 3Gi
      requests:
        cpu: 2000m
        memory: 1Gi
  reportsController:
    image:
      registry: artifactory.algol60.net
      repository: csm-docker/stable/ghcr.io/kyverno/reports-controller
      tag: v1.13.4
    resources:
      limits:
        cpu: 6000m
        memory: 3Gi
      requests:
        cpu: 2000m
        memory: 1Gi
  backgroundController:
    image:
      registry: artifactory.algol60.net
      repository: csm-docker/stable/ghcr.io/kyverno/background-controller
      tag: v1.13.4
    resources:
      limits:
        cpu: 6000m
        memory: 3Gi
      requests:
        cpu: 2000m
        memory: 1Gi
  cleanupJobs:
    admissionReports:
      image:
        registry: artifactory.algol60.net
        repository: csm-docker/stable/docker.io/bitnami/kubectl
        tag: 1.33.1
    clusterAdmissionReports:
      image:
        registry: artifactory.algol60.net
        repository: csm-docker/stable/docker.io/bitnami/kubectl
        tag: 1.33.1
  webhooksCleanup:
    image: 
      registry: artifactory.algol60.net
      repository: csm-docker/stable/docker.io/bitnami/kubectl
      tag: 1.33.1
  policyReportsCleanup:
    image: 
      registry: artifactory.algol60.net
      repository: csm-docker/stable/docker.io/bitnami/kubectl
      tag: 1.33.1   
  buildKyvernoTrust:
    rbac:
      create: true
      saccount:
        name: post-install-job
    image:
      registry: artifactory.algol60.net
      repository: csm-docker/stable/docker.io/bitnami/kubectl
      tag: 1.33.1
  deleteCrd:
    enabled: true
    rbac:
      create: true
      saccount:
        name: pre-upgrade-job
    image:
      registry: artifactory.algol60.net
      repository: csm-docker/stable/docker.io/bitnami/kubectl
      tag: 1.33.1      



