# Default values for cray-kyverno.
# This is a YAML-formatted file.
kyverno:
  image:
    repository: artifactory.algol60.net/csm-docker/stable/ghcr.io/kyverno/kyverno
    tag: v1.9.5
  resources:
    limits:
      cpu: 6000m
      memory: 3Gi
    requests:
      cpu: 2000m
      memory: 1Gi
  initImage:
    registry:
    repository: artifactory.algol60.net/csm-docker/stable/ghcr.io/kyverno/kyvernopre
    tag: v1.9.5
  initResources:
    limits:
      cpu: 6000m
      memory: 3Gi
    requests:
      cpu: 2000m
      memory: 1Gi
  testImage:
    repository: artifactory.algol60.net/csm-docker/stable/docker.io/library/busybox
    tag: 1.28.0-glibc
  securityContext:
    seccompProfile: null
  cleanupController:
    # -- Disable cleanup controller since it is not production ready.
    # -- If cleanup controller is enabled then need to enable rbac as well
    enabled: false
    rbac:
      create: false
      saccount:
        name: kyverno-cleanup-controller
    image:
      repository: artifactory.algol60.net/csm-docker/stable/ghcr.io/kyverno/cleanup-controller
      tag: v1.9.5
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - kyverno
        topologyKey: kubernetes.io/hostname

  priorityClassName: csm-high-priority-service
 # Desired number of pods/replica
  replicaCount: 3
  config:
    webhooks: [{"namespaceSelector":{"matchExpressions":[{"key":"kubernetes.io/metadata.name","operator":"NotIn","values":["kyverno","kube-system"]}]}}]
