# Default values for cray-kyverno.
# This is a YAML-formatted file.
kyverno:
  image:
    repository: artifactory.algol60.net/csm-docker/stable/ghcr.io/kyverno/kyverno
    tag: v1.6.2
  resources:
    limits:
      cpu: 600m
      memory: 3Gi
    requests:
      cpu: 200m
      memory: 1Gi
  initImage:
    registry:
    repository: artifactory.algol60.net/csm-docker/stable/ghcr.io/kyverno/kyvernopre
    tag: v1.6.2
  initResources:
    limits:
      cpu: 600m
      memory: 3Gi
    requests:
      cpu: 200m
      memory: 1Gi
  testImage:
    repository: artifactory.algol60.net/csm-docker/stable/docker.io/library/busybox
    tag: 1.28.0-glibc
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - kyverno
        topologyKey: kubernetes.io/hostname

  priorityClassName: csm-high-priority-service
 # Desired number of pods/replica
  replicaCount: 3
